name: Your New Jekyll Site
markdown: rdiscount
pygments: true
encoding: UTF-8

exclude: [config.rb, Gruntfile.js, package.json, sass, blog.sublime-project, blog.sublime-workspace, node_modules]

permalink: none

navigation:
  - label: 玩玩编程
    alias: coding
  - label: 剽窃代码
    alias: snippets
  - label: 鼓捣工具
    alias: tools
